### ISSUE TITLE
Privacy issue with mixpanel

### ISSUE THREAD

**Issue by super-kamil** [wrakky/page-ruler#101]
![image](https://user-images.githubusercontent.com/708028/35856942-d1d91bbc-0b37-11e8-87ce-8c95d1682258.png)

Even with disabled option to send tracking data the mixpanel script is injected! This is not acceptable.

**Comment by mischkl** [comment]
Same problem here.

**Comment by wrakky** [comment]
I no longer have control over the distributed version of the extension through the Chrome Store so this is not something I can address I'm afraid. Whatever "mixpanel" is was not something that was included in the codebase when I was in control of it and all the extension used to do was send usage statistics of different features to Google Analytics (which the disabled tracking feature respected) so the new owner must have added this feature.

**Comment by GridTrekkor** [comment]
Could you zip up the previous version and commit it here?  We can load it through the extensions page rather than the Chrome Webstore.

**Comment by siddarthvader** [comment]
+1
facing this issue, had to uninstall all extensions in order to find out, is this burglary?

[Mixpanel (an analytics service) was inadvertently collecting user passwords for months.l](https://twitter.com/s_englehardt/status/96056309015162880)

**Comment by wrakky** [comment]
No not burglary. It's been 3 years since I've had a chance to work on it so I passed it onto someone else who must have made these changes.

The original codebase is still available on the [original_source_code branch](https://github.com/wrakky/page-ruler/tree/original_source_code) so you can build it from there if you want to.

**Comment by shivanshu3** [comment]
This is what was injected. Some of it looks kind of sketch. I have uninstalled it.
https://gist.github.com/shivanshu3/45817d2354e41ca858c915b556a7174a

**Comment by vteremasov** [comment]
I reported abuse. It looks like a malware.

**Comment by Esteban-Rocha** [comment]
@wrakky You should pass along the information of the new maintainer so the community can address this privacy issue directly, this behavior it's unacceptable.

**Comment by Esteban-Rocha** [comment]
https://twitter.com/random_walker/status/960536723095719937 

@wrakky You stated an update it's coming, just an easy and quick question then, ¿are you going to make the source code for it open source? I cannot trust anything that comes from you unfortunately as facts speak for them selves, I'm not a chrome js ext developer but hell I rather build a fork from this, too sad this was an incredible web developer tool but it's clear to me what the motivations behind this are.

**Comment by mildfuzz** [comment]
unacceptable for a thing you didn't pay for to do a thing you're not happy with?

**Comment by wrakky** [comment]
Ok clearly this isn't great and not what I wanted at all.

The new owner is currently replying to negative reviews on the extension page claiming that an option to disable the mixpanel stuff is coming soon - whether you want to believe him or not is up to you. He is also different to the person I passed the account onto as well so I don't know who he is.

The code was licensed under MIT and is fully open source and available, like I said above, on the [original_source_code)(https://github.com/wrakky/page-ruler/tree/original_source_code). If anyone wants to fork it they are free to do so and run that locally or even publish a new version themselves in the extension store.

There isn't anything else I can do about this unfortunately.

**Comment by Esteban-Rocha** [comment]
It's clear to me that they selled it to someone related to mixpanel, that "Since at least March 2017, they've been (unintentionally) harvesting user passwords." it's just crap, they are not retarded to not know what they do.

At the very least you should make clear that your not longer the maintainer because you selled it or whatever, in the chrome store the support panel and the website goes all way back to you, so you better make "Frank" or the person in charge update that info as you are clearly not the person responsible for this, and you cannot do anything here to address this issue.

**Comment by wrakky** [comment]
Let me know if you do publish a new version and I'll link to it from here.

**Comment by wrakky** [comment]
@Esteban-Rocha I'm going to archive this project because people don't read things. Tag me in your repo if you publish a new version and I'll update the details here.
